---
deployment:
  tasks:
    - command: "php composer.phar self-update"
    - command: "php composer.phar update --no-dev"
      cwd: /home/sopleudy/public_html  # Replace with your app's actual path
      timeout: 600  # Optional: Adjust the timeout as needed
